[package]
name = "creek"
version = "0.1.0"
authors = ["findus11 <findusxi@protonmail.com>"]
license-file = "LICENSE"
edition = "2018"

[features]
default = ["fnv"]
no-deps = []

[dependencies]
fnv = { version = "1.0", optional = true }